# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyBR1VdywBXe3tOLnWIYQTj9fX5dJoKOn38"
GEMINI_MODEL_NAME = "gemini-1.5-flash"
# If you use OpenAI, add your key here
OPENAI_API_KEY = "sk-AXjlmoGMOipZl9ds_gqT_w"
OPENAI_MODEL_NAME = "GPT-4o-mini"