# .streamlit/secrets.toml
# If you use OpenAI, add your key here
OPENAI_API_KEY = "sk-O4PdvzLn7nqA-2B00MFcYA"
CHAT_MODEL = "GPT-4o-mini"
EMBED_MODEL_API_KEY = "sk-CWONfrNdWW0VGI5xlLY8ww"
EMBED_MODEL = 'text-embedding-3-small'
BASE_URL = "https://aiportalapi.stu-platform.live/jpe"
PINECONE_API_KEY = "pcsk_kEAzt_2Rf2Pvovncdmopjefx73XhhT23SYDd3HZ5DFkF8v4JwS6JN6frTMd3wf81JgrJC"
PINECONE_INDEX_NAME = 'elevate_ai'
