# .streamlit/secrets.toml

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
GEMINI_MODEL_NAME = "gemini-1.5-flash"

# If you use OpenAI, add your key here
# OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"
# OPENAI_MODEL_NAME = "gpt-4o-mini"

# MongoDB Configuration (cloud connection)
MONGODB_URI = "mongodb+srv://<username>:<password>@<your-cluster>.mongodb.net/?retryWrites=true&w=majority&appName=<AppName>"
MONGODB_NAME = "resumeScan"
MONGODB_COLLECTION = "cv_files"